site_name: sharp
site_description: 高性能节点。js图像处理，是调整JPEG、PNG、WebP和TIFF图像大小的最快模块。

site_url: http://sharp.pixelplumbing.com/
repo_url: https://github.com/lovell/sharp

copyright: <a href="https://pixelplumbing.com/">pixelplumbing.com</a>
# google_analytics: ['UA-13034748-12', 'sharp.pixelplumbing.com']

theme:
  name: material
  language: zh
  feature:
    tabs: true

markdown_extensions:
  - toc:
      permalink: True
pages:
  - 主页: index.md
  - 安装: install.md
  - API:
    - 构造函数: api-constructor.md
    - 输入: api-input.md
    - 输出: api-output.md
    - 调整图片大小: api-resize.md
    - 合成图像: api-composite.md
    - 图像操作: api-operation.md
    - 颜色操纵: api-colour.md
    - 通道操作: api-channel.md
    - 实用程序: api-utility.md
  - 性能: performance.md
  - 更新日志: changelog.md
